:ZYUV_GEN = ''; 
SELECT SQL.TMPFILE INTO :ZYUV_GEN FROM DUMMY ; 
LINK GENERALLOAD TO :ZYUV_GEN ; 
GOTO 9988 WHERE :RETVAL <= 0 ;
/*****/
DECLARE C CURSOR FOR 
SELECT
DOCUMENTS.DOCNO,
DOCUMENTS.DOC
FROM DOCUMENTS,TODOLIST,DOCSTATUSES,USERS,SERVCONT
WHERE DOCUMENTS.TYPE = 'Z'
AND TODOLIST.IV = DOCUMENTS.DOC
AND SERVCONT.DOC = DOCUMENTS.DOC
AND DOCSTATUSES.DOCSTATUS = TODOLIST.DOCSTATUS
AND USERS.USER = TODOLIST.USER
AND USERS.USER = 1 
AND TODOLIST.UDATE > 29/05/23
AND SERVCONT.EXPIRYDATE > 01/06/23
/*AND DOCUMENTS.DOCNO = 'SR21000049'*/ ; 
OPEN C  ; 
GOTO 90 WHERE :RETVAL <= 0 ; 
LABEL 10 ; 
:DOCNO = ''; 
:DOC = 0 ; 
FETCH C INTO :DOCNO,:DOC ; 
GOTO 80 WHERE :RETVAL <= 0 ;
 /*****/
 :ZYUV_LAST = ''; 
 :ZYUV_UDATE = 01/01/88 ; 
 SELECT
 DOCSTATUSES.STATDES,
 TODOLIST.UDATE
 INTO :ZYUV_LAST,:ZYUV_UDATE
 FROM DOCUMENTS,TODOLIST,DOCSTATUSES,USERS
 WHERE DOCUMENTS.TYPE = 'Z'
AND TODOLIST.IV = DOCUMENTS.DOC
AND TODOLIST.TYPE = 'Z'
AND DOCSTATUSES.DOCSTATUS = TODOLIST.DOCSTATUS
AND USERS.USER = TODOLIST.USER
AND TODOLIST.UDATE < 01/06/23
AND DOCUMENTS.DOC = :DOC  
ORDER BY 2 DESC ; 
:LINE = 0 ; 
SELECT MAX(LINE) INTO :LINE 
FROM GENERALLOAD ; 
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,INT1,TEXT1)
VALUES (:LINE +1,'1',:DOC,:ZYUV_LAST) ; 
LOOP 10 ; 
LABEL 80  ; 
CLOSE C ;
LABEL 90 ;
SELECT

LINE,
RECORDTYPE,
INT1,
TEXT1
FROM GENERALLOAD FORMAT ; 
EXECUTE INTERFACE 'ZPBO_ENDTOKEF',SQL.TMPFILE,'-L',:ZYUV_GEN ; 
UNLINK GENERALLOAD ; 
LABEL 9988 ;  